- name: Download file from SharePoint
  hosts: localhost
  vars:
    sharepoint_url: "https://example.sharepoint.com/sites/mysite"
    file_path: "/Shared%20Documents/example.txt"
    username: "exampleuser"
    password: "examplepassword"
    download_directory: "/home/user/downloads"
  tasks:
    - name: Get authentication cookies
      uri:
        url: "{{ sharepoint_url }}/_forms/default.aspx?wa=wsignin1.0"
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        return_content: yes
      register: auth_result
    - name: Download file
      get_url:
        url: "{{ sharepoint_url }}{{ file_path }}"
        headers:
          Cookie: "{{ auth_result.cookies['FedAuth'] }}; {{ auth_result.cookies['rtFa'] }}"
        dest: "{{ download_directory }}/example.txt"
